version: '3' 
services:
  zeppelin:
    image: openkbs/docker-spark-bde2020-zeppelin
    build:
      context: .
      args:
        APACHE_SPARK_VERSION: 2.1.0 
        APACHE_HADOOP_VERSION: 2.8.0 
        SPARK_MASTER: "spark://spark-master:7077" 
        ZEPPELIN_DOWNLOAD_URL: http://apache.cs.utah.edu/zeppelin 
        ZEPPELIN_VERSION: 0.7.2 
        ZEPPELIN_PORT: 8080 
        ZEPPELIN_INSTALL_DIR: /usr/lib 
        ZEPPELIN_HOME: /usr/lib/zeppelin 
        ZEPPELIN_PKG_NAME: zeppelin-${ZEPPELIN_VERSION}-bin-all 
    container_name: zeppelin
#    depends_on:
#      - spark-master
#      - namenode
    environment:
      CORE_CONF_fs_defaultFS: "hdfs://namenode:8020"
      SPARK_MASTER: "spark://spark-master:7077"
      MASTER: "spark://spark-master:7077"
      ZEPPELIN_PORT: 8080
      ZEPPELIN_JAVA_OPTS: >-
        -Dspark.driver.memory=1g
        -Dspark.executor.memory=2g
      MASTER: spark://spark-master:7077
    ports:
      - 19090:8080
    env_file:
      - ./hadoop-hive.env
    volumes:
      - ${HOME}/data-docker/docker-spark-bde2020-zeppelin/data:/usr/lib/zeppelin/data:rw
      - ${HOME}/data-docker/docker-spark-bde2020-zeppelin/notebook:/usr/lib/zeppelin/notebook:rw
    command: /usr/lib/zeppelin/bin/zeppelin.sh

